### ISSUE TITLE
Self-deserializing feature

### ISSUE THREAD

**Issue by NickDarvey** [nokia/ts-serialize-closures#13]
I was wondering if you've explored- or might have some ideas on how to explore adding a self-deserializing feature? i.e. where the receiver of a serialized function need not have `serialize-closures` installed but only needs to `eval()` it.
I imagine this might involve serializing the deserializer (and `SerializedGraph`, etc.) in some way but wasn't quite sure where to begin.

**Comment by lhoste-bell** [comment]
Hi @NickDarvey,

We have not tried this ourselves. Would it work if you webpack-bundle the `serialize-closures` library and a little bit of bootstraping code for the de-serialization process?

**Comment by NickDarvey** [comment]
@lhoste-bell webpack-bundling is a good idea, I shall give it a go :)
